name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: 21v1u5
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake-dark.svg
      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "generate contribution snake" || echo "No changes to commit"
          git push
